var a =4.389

console.log(Math.floor(a))
console.log(Math.abs(a))
console.log(Math.ceil(a))
console.log(Math.round(a))
console.log(Math.max(400,500))
console.log(Math.min(500,300))
console.log(Math.pow(2,3))
console.log(Math.sqrt(9))
console.log(Math.sqrt(64))
console.log(Math.round(Math.random()*50+1))
console.log(Math.round(a))
console.log(Math.ceil(a))
console.log(Math.pow(3,4))